# Generated by Django 5.2.7 on 2025-10-16 00:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('verificado', models.BooleanField(default=False)),
                ('token_verificacion', models.UUIDField(default=uuid.uuid4)),
                ('es_participante', models.BooleanField(default=False)),
                ('es_ganador', models.BooleanField(default=False)),
                ('fecha_inscripcion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
    ]
